name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: '*/20 * * * *' # 每20分钟执行一次
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v2
      - name: Cloudflare pages build
        uses: Cyb3r-Jak3/actions-cloudflare-pages@v1.0.1
        with:
         account: ${{ secrets.CLOUDFLARE_ZONE }}
         project: ${{ secrets.CLOUDFLARE_PROJECT }}
         email: ${{ secrets.CLOUDFLARE_EMAIL }}
         global_token: ${{ secrets.CLOUDFLARE_KEY }}
